buildJS:
  tags:
    - docker
  image: trzeci/emscripten
  script:
    - pushd emscripten
    - ./buildToolkit -DHP
    - ls build
    - popd
    - git archive $(git rev-parse HEAD) -o verovio.tar.gz
  artifacts:
    paths:
      - emscripten/build/verovio-toolkit.js
      - LICENSE.txt
      - verovio.tar.gz
  cache:
    paths:
      - emscripten/data
      - emscripten/build

buildBIN:
  tags:
    - docker
  image: buildpack-deps:stable-scm
  before_script:
    - (apt-get update || apt-get update) && apt-get install -y git cmake build-essential
  script:
    - pushd tools
    - cmake . && make && make install/strip
    - popd
  artifacts:
    paths:
      - /usr/local/bin/verovio
      - /usr/local/share/verovio
