build:
  image: trzeci/emscripten
  tags:
    - docker
  script:
    - cd emscripten
    - ./buildToolkit -DHP
    - ls build
  artifacts:
    paths:
      - emscripten/build/verovio-toolkit.js
  cache:
    paths:
      - emscripten/data
      - emscripten/build
